Repository viperproject/VerifiedSCION, pull requests merged in 2024-03, with the labels that each got.

#266 Bring changes of `libepic` from PR #261
  pkg/experimental/epic/epic.go
  pkg/slayers/scion_spec.gobra
  verification/dependencies/crypto/aes/cipher.gobra
  verification/dependencies/crypto/cipher/cbc.gobra
  verification/dependencies/crypto/cipher/cipher.gobra
Labels: memory-safety

#265 experiment with disabling NL
  .github/workflows/gobra.yml
Labels: CI, performance

#268 widen lemma for absIO_val
  router/io-spec.gobra
  router/widen-lemma.gobra
  verification/io/io-spec.gobra
Labels: IO

#263 Verify send guard in Run
  router/dataplane.go
  router/dataplane_concurrency_model.gobra
  router/io-spec.gobra
  router/widen-lemma.gobra
  verification/io/io-spec.gobra
Labels: IO
